'use strict';

const $ = id => document.getElementById(id);
const STORE = 'astrowindow.v2';
const DAY = 86400000;
const DEFAULT = {
  lang:'en', red:false, activeView:'dashboard', selectedDate:null, selectedTarget:'WR 134',
  activePlace:1, places:[
    {id:1,name:'Sderot, Israel',lat:31.5235,lon:34.5931,bortle:8,sqm:null,window:{enabled:false,left:90,right:270,bottom:25,top:85}},
    {id:2,name:'Shittim / Negev',lat:30.33,lon:34.95,bortle:3,sqm:null,window:{enabled:false,left:0,right:360,bottom:15,top:90}}
  ],
  activeRig:1, rigs:[
    {id:1,name:'FRA400 + reducer · 2600MC · L-Ultimate',focal:280,aperture:72,sensorW:23.5,sensorH:15.7,pixel:3.76,filter:'haoiii',mount:'medium',wind:20,minAlt:30},
    {id:2,name:'FRA400 native · 2600MC · L-Ultimate',focal:400,aperture:72,sensorW:23.5,sensorH:15.7,pixel:3.76,filter:'haoiii',mount:'medium',wind:20,minAlt:30},
    {id:3,name:'FRA400 native · 2600MC · Askar E2',focal:400,aperture:72,sensorW:23.5,sensorH:15.7,pixel:3.76,filter:'siioiii',mount:'medium',wind:20,minAlt:30}
  ],
  limits:{minAlt:30,cloud:20,dew:2,window:1.5}, bookmarks:['WR 134','Crescent Nebula (NGC 6888)','Flying Bat (Sh2-129)'], plans:{}, compositions:{}
};

const DSO = [
 ['Andromeda Galaxy (M31)','Galaxy',10.685,41.269,190,60,35,'broadband'],['Triangulum Galaxy (M33)','Galaxy',23.462,30.66,73,45,35,'broadband'],['Whirlpool Galaxy (M51)','Galaxy',202.47,47.195,11,7,40,'broadband'],['Pinwheel Galaxy (M101)','Galaxy',210.803,54.349,29,27,35,'broadband'],['Bode’s Galaxy (M81)','Galaxy',148.888,69.065,27,14,35,'broadband'],['Cigar Galaxy (M82)','Galaxy',148.969,69.68,11,5,35,'broadband'],['Leo Triplet','Galaxy',169.75,13.15,70,40,32,'broadband'],
 ['Orion Nebula (M42)','Emission',83.822,-5.391,85,60,20,'haoiii'],['Horsehead Nebula (B33)','Dark',85.25,-2.45,60,40,25,'broadband'],['Rosette Nebula (Sh2-275)','Emission',97.95,4.95,80,65,25,'haoiii'],['California Nebula (NGC 1499)','Emission',60.65,36.4,160,40,28,'haoiii'],['Heart Nebula (IC 1805)','Emission',38.3,61.45,150,150,28,'haoiii'],['Soul Nebula (IC 1848)','Emission',44.5,60.43,150,75,28,'haoiii'],['Heart & Soul Mosaic','Emission',41.5,60.9,310,180,25,'haoiii'],['Flaming Star (IC 405)','Emission',79.1,34.27,37,19,28,'haoiii'],['Tadpoles (IC 410)','Emission',82.42,33.41,40,30,28,'haoiii'],['NGC 1893','Emission',80.72,33.41,25,25,30,'haoiii'],
 ['North America (NGC 7000)','Emission',314.75,44.33,120,100,25,'haoiii'],['Pelican Nebula (IC 5070)','Emission',312.75,44.4,85,70,25,'haoiii'],['Sadr Region (IC 1318)','Emission',305.5,40.25,180,120,22,'haoiii'],['Veil Nebula Complex','SNR',312.5,30.7,180,150,25,'haoiii'],['Eastern Veil (NGC 6992)','SNR',313.0,31.72,70,10,25,'haoiii'],['Western Veil (NGC 6960)','SNR',311.4,30.72,70,10,25,'haoiii'],['Crescent Nebula (NGC 6888)','Emission',303.03,38.35,20,10,35,'haoiii'],['Flying Bat (Sh2-129)','Emission',319.75,59.9,140,140,25,'haoiii'],['Squid Nebula (Ou4)','Emission',319.9,59.6,75,25,38,'oiii'],['WR 134','Emission',302.1,36.0,40,40,35,'haoiii'],['Sh2-132 Lion Nebula','Emission',334.5,56.0,90,60,28,'haoiii'],['Elephant Trunk (IC 1396)','Emission',324.75,57.5,170,140,25,'haoiii'],['Wizard Nebula (NGC 7380)','Emission',342.1,58.13,25,20,32,'haoiii'],['Bubble Nebula (NGC 7635)','Emission',350.2,61.2,15,8,38,'haoiii'],
 ['Lagoon Nebula (M8)','Emission',270.93,-24.38,90,40,22,'haoiii'],['Trifid Nebula (M20)','Emission',270.63,-23.03,28,28,28,'haoiii'],['Eagle Nebula (M16)','Emission',274.7,-13.8,35,28,25,'haoiii'],['Omega Nebula (M17)','Emission',275.2,-16.18,46,37,25,'haoiii'],['Rho Ophiuchi','Reflection',246.65,-24.45,300,240,18,'broadband'],
 ['Pleiades (M45)','Reflection',56.75,24.12,110,110,22,'broadband'],['Iris Nebula (NGC 7023)','Reflection',315.4,68.17,18,18,35,'broadband'],['NGC 1333','Reflection',52.3,31.3,20,15,35,'broadband'],['Witch Head (IC 2118)','Reflection',75.0,-7.2,180,60,22,'broadband'],
 ['Dumbbell Nebula (M27)','Planetary',299.9,22.72,8,6,42,'oiii'],['Ring Nebula (M57)','Planetary',283.4,33.03,1.4,1.0,48,'oiii'],['Helix Nebula (NGC 7293)','Planetary',337.4,-20.84,25,20,28,'oiii'],['Pacu Man (NGC 281)','Emission',13.0,56.62,35,30,30,'haoiii'],['NGC 7822','Emission',0.75,67.15,60,40,30,'haoiii'],['Double Cluster','Cluster',35.0,57.13,60,30,25,'broadband']
].map((d,i)=>({id:i,name:d[0],type:d[1],ra:d[2],dec:d[3],w:d[4],h:d[5],minAlt:d[6],signal:d[7]}));

let state = loadState(), weather=null, nights=[], evaluations=[], timelineChart=null, targetChart=null;
let sensorStep=0, sensorHeading=null, sensorAltitude=null;
let aladin=null, compositionTarget=null, compositionViewFov=1, frameState=null;
let locationMap=null, locationMarker=null, mapSelection=null, mapEditingId=null;
const SENSOR_STEPS=[
  {key:'left',title:'Point to the LEFT edge',instruction:'Aim the back of your phone at the left edge of the opening. This captures compass azimuth.',value:'heading'},
  {key:'right',title:'Point to the RIGHT edge',instruction:'Aim at the right edge of the opening. The window may cross north (0°); that is supported.',value:'heading'},
  {key:'bottom',title:'Point to the BOTTOM edge',instruction:'Aim at the lowest usable line above roofs, trees or walls. This captures altitude.',value:'altitude'},
  {key:'top',title:'Point to the TOP edge',instruction:'Aim at the highest visible line of the opening. This captures altitude.',value:'altitude'}
];
function loadState(){try{return merge(structuredClone(DEFAULT),JSON.parse(localStorage.getItem(STORE)||'{}'))}catch{return structuredClone(DEFAULT)}}
function merge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k]) merge(a[k],b[k]);else a[k]=b[k]}return a}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
const place=()=>state.places.find(x=>x.id===state.activePlace)||state.places[0];
const rig=()=>state.rigs.find(x=>x.id===state.activeRig)||state.rigs[0];
function skyWindow(){return place().window||{enabled:false,left:0,right:360,bottom:state.limits.minAlt,top:90}}
const clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x));
const rad=x=>x*Math.PI/180, deg=x=>x*180/Math.PI;
const round=(x,n=0)=>Number(x).toFixed(n);
const fmtDate=d=>d.toISOString().slice(0,10);
function siteFmt(d,opts={hour:'2-digit',minute:'2-digit'}){return new Intl.DateTimeFormat(state.lang==='he'?'he-IL':'en-GB',{...opts,timeZone:weather?.timezone||'UTC',hour12:false}).format(d)}
function parseWeatherTime(s){return new Date(Date.parse(s+'Z')-(weather?.utc_offset_seconds||0)*1000)}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}

document.addEventListener('DOMContentLoaded',init);
async function init(){
  state.selectedDate ||= fmtDate(new Date());
  bind(); applyPrefs(); renderStatic(); await refresh();
  if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
}
function bind(){
  document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
  $('refreshButton').onclick=refresh;$('redButton').onclick=()=>{state.red=!state.red;save();applyPrefs()};$('langButton').onclick=()=>{state.lang=state.lang==='en'?'he':'en';save();applyPrefs();renderAll()};
  $('nightDate').onchange=e=>{state.selectedDate=e.target.value;save();renderAll()};$('prevDate').onclick=()=>shiftDate(-1);$('nextDate').onclick=()=>shiftDate(1);
  $('placeButton').onclick=()=>switchView('places');$('gpsButton').onclick=useGPS;$('placeForm').onsubmit=addPlace;$('mapPickerButton').onclick=()=>openMapPicker();$('closeMap').onclick=closeMapPicker;$('mapSearchButton').onclick=searchMapPlace;$('mapSearchInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();searchMapPlace()}};$('mapUseGPS').onclick=centerMapOnGPS;$('saveMapLocation').onclick=saveMapLocation;
  $('mainWindowToggle').onchange=e=>{place().window={...skyWindow(),enabled:e.target.checked};save();fillRig();renderAll();toast(e.target.checked?'Sky-window filtering enabled':'Sky-window filtering disabled')};$('editMainWindow').onclick=()=>switchView('settings');
  $('rigSelect').onchange=e=>{state.activeRig=+e.target.value;save();fillRig();renderAll()};$('rigForm').onsubmit=saveRig;$('newRigButton').onclick=newRig;$('saveHorizon').onclick=saveHorizon;
  $('calibrateWindow').onclick=startWindowCalibration;$('cancelSensor').onclick=stopWindowCalibration;$('captureSensor').onclick=captureWindowBoundary;
  ['minTargetAlt','cloudLimit','dewLimit','windowLimit'].forEach(id=>$(id).onchange=()=>{state.limits.minAlt=+$('minTargetAlt').value;state.limits.cloud=+$('cloudLimit').value;state.limits.dew=+$('dewLimit').value;state.limits.window=+$('windowLimit').value;save();renderAll()});
  $('targetSearch').oninput=renderTargets;$('targetType').onchange=renderTargets;$('bookmarksOnly').onchange=renderTargets;
  $('closeDialog').onclick=()=>$('targetDialog').close();$('planButton').onclick=()=>{buildPlan();switchView('plan')};$('autoPlanButton').onclick=buildPlan;$('addPlanTarget').onclick=addManualPlanTarget;$('clearPlanButton').onclick=clearPlan;$('savePlanButton').onclick=savePlan;$('exportButton').onclick=exportPlan;
  $('rotationSlider').oninput=e=>{if(!frameState)return;frameState.rotation=+e.target.value;applyFrame();updateCompositionStatus()};$('centerFrame').onclick=()=>{if(!frameState)return;frameState.x=50;frameState.y=50;frameState.rotation=0;applyFrame();updateCompositionStatus()};$('saveFrame').onclick=saveComposition;$('surveySelect').onchange=changeSurvey;
}
function applyPrefs(){document.body.classList.toggle('red-mode',state.red);document.documentElement.dir=state.lang==='he'?'rtl':'ltr';$('langButton').textContent=state.lang==='en'?'HE':'EN'}
function switchView(id){state.activeView=id;save();document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='targets')renderTargets();if(id==='plan')openPlan();scrollTo(0,0)}
function shiftDate(n){const d=new Date(state.selectedDate+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);state.selectedDate=fmtDate(d);$('nightDate').value=state.selectedDate;save();renderAll()}

async function refresh(){
  $('refreshButton').disabled=true;$('decision').textContent='Updating forecast…';
  const p=place();
  const hourly='temperature_2m,relative_humidity_2m,dew_point_2m,precipitation_probability,precipitation,cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,visibility,wind_speed_10m,wind_gusts_10m,wind_direction_10m';
  try{
    const u=`https://api.open-meteo.com/v1/forecast?latitude=${p.lat}&longitude=${p.lon}&hourly=${hourly}&timezone=auto&forecast_days=8`;
    const response=await fetch(u);if(!response.ok)throw Error(response.status);weather=await response.json();weather.fetchedAt=new Date().toISOString();localStorage.setItem('astrowindow.weather.'+p.id,JSON.stringify(weather));
    try{weather.modelSpread=await fetchModelSpread(p)}catch{weather.modelSpread=null}
  }catch(e){const cached=localStorage.getItem('astrowindow.weather.'+p.id);if(cached){weather=JSON.parse(cached);$('offlineNotice').classList.remove('hidden')}else{$('decision').textContent='Forecast unavailable';$('decisionReason').textContent='Check your connection and refresh.';return}}
  finally{$('refreshButton').disabled=false}
  renderAll();
}
async function fetchModelSpread(p){
  const u=`https://api.open-meteo.com/v1/forecast?latitude=${p.lat}&longitude=${p.lon}&hourly=cloud_cover,wind_speed_10m&models=icon_seamless,gfs_seamless,ecmwf_ifs025&timezone=auto&forecast_days=8`;
  const r=await fetch(u);if(!r.ok)throw Error();const j=await r.json();return j.hourly;
}

function makeNight(dateString){
  const p=place(), noon=new Date(dateString+'T12:00:00Z'), t=SunCalc.getTimes(noon,p.lat,p.lon), next=SunCalc.getTimes(new Date(noon.getTime()+DAY),p.lat,p.lon);
  const dusk=t.night, dawn=next.nightEnd, midpoint=new Date((dusk.getTime()+dawn.getTime())/2), illum=SunCalc.getMoonIllumination(midpoint);
  return {date:dateString,dusk,dawn,sunset:t.sunset,sunrise:next.sunrise,midpoint,illum};
}
function hoursForNight(n){
  if(!weather)return[];return weather.hourly.time.map((s,i)=>({
    time:parseWeatherTime(s),temp:weather.hourly.temperature_2m[i],humidity:weather.hourly.relative_humidity_2m[i],dew:weather.hourly.dew_point_2m[i],precipProb:weather.hourly.precipitation_probability[i],precip:weather.hourly.precipitation[i],cloud:weather.hourly.cloud_cover[i],low:weather.hourly.cloud_cover_low[i],mid:weather.hourly.cloud_cover_mid[i],high:weather.hourly.cloud_cover_high[i],visibility:weather.hourly.visibility[i],wind:weather.hourly.wind_speed_10m[i],gust:weather.hourly.wind_gusts_10m[i],windDir:weather.hourly.wind_direction_10m[i]
  })).filter(x=>x.time>=n.dusk&&x.time<=n.dawn)}
function weatherQuality(h){
  const r=rig(), dewGap=h.temp-h.dew;
  let s=100-h.cloud*1.05-Math.max(0,h.gust-r.wind)*2.4-Math.max(0,h.wind-r.wind)*1.4-h.precipProb*.7;
  if(h.precip>0)s-=55;if(dewGap<state.limits.dew)s-=22;if(h.humidity>92)s-=12;if(h.visibility<10000)s-=10;
  return clamp(Math.round(s));
}
function getGMST(d){const jd=d.getTime()/DAY+2440587.5;return((280.46061837+360.98564736629*(jd-2451545))%360+360)%360}
function azAlt(d,obj){
  const p=place(),ha=rad((((getGMST(d)+p.lon-obj.ra+540)%360)-180)),dc=rad(obj.dec),ph=rad(p.lat),sa=Math.sin(dc)*Math.sin(ph)+Math.cos(dc)*Math.cos(ph)*Math.cos(ha),alt=Math.asin(sa),az=Math.atan2(-Math.sin(ha)*Math.cos(dc),Math.sin(dc)*Math.cos(ph)-Math.cos(dc)*Math.sin(ph)*Math.cos(ha));
  return{alt:deg(alt),az:(deg(az)+360)%360};
}
function insideWindowAz(az){const w=skyWindow();if(!w.enabled)return true;return w.left<=w.right?(az>=w.left&&az<=w.right):(az>=w.left||az<=w.right)}
function insideSkyWindow(az,alt){const w=skyWindow();return insideWindowAz(az)&&(!w.enabled||(alt>=w.bottom&&alt<=w.top))}
function moonAt(d){const m=SunCalc.getMoonPosition(d,place().lat,place().lon);return{alt:deg(m.altitude),az:(deg(m.azimuth)+180+360)%360}}
function separation(a,b){return deg(Math.acos(clamp(Math.sin(rad(a.alt))*Math.sin(rad(b.alt))+Math.cos(rad(a.alt))*Math.cos(rad(b.alt))*Math.cos(rad(a.az-b.az)),-1,1)))}
function optics(){const r=rig();return{fRatio:r.focal/r.aperture,scale:206.265*r.pixel/r.focal,fovW:deg(2*Math.atan(r.sensorW/(2*r.focal))),fovH:deg(2*Math.atan(r.sensorH/(2*r.focal)))}}
function filterFit(o,moonIll,sep){const f=rig().filter;let s=100;if(f==='broadband'&&o.signal!=='broadband')s-=12;if(f!=='broadband'&&['Galaxy','Reflection','Dark','Cluster'].includes(o.type))return 5;if(f==='siioiii'&&o.signal==='haoiii')s-=18;if(f==='haoiii'&&o.signal==='oiii')s-=5;if(moonIll>.55){if(f==='broadband')s-=Math.max(0,65-sep)*.9+moonIll*30;else s-=Math.max(0,35-sep)*.35}return clamp(s)}
function sqmFromBortle(b){const table=[[1,21.9],[2,21.65],[3,21.4],[4,20.85],[5,19.75],[6,18.55],[7,17.4],[8,16.5],[9,15.5]];b=clamp(b,1,9);const lo=Math.floor(b),hi=Math.ceil(b);if(lo===hi)return table[lo-1][1];return table[lo-1][1]+(table[hi-1][1]-table[lo-1][1])*(b-lo)}
function lightPollutionFit(o){const p=place(),sqm=p.sqm||(+p.bortle?sqmFromBortle(+p.bortle):null);if(!sqm)return 82;const loss=clamp((21.8-sqm)/6.3,0,1),f=rig().filter;let penalty=loss*(f==='broadband'?55:f==='haoiii'?18:f==='siioiii'?14:10);if(['Galaxy','Reflection','Dark'].includes(o.type)&&f==='broadband')penalty+=loss*18;return clamp(Math.round(100-penalty))}
function framing(o){const f=optics(),fit=Math.max(o.w/(f.fovW*60),o.h/(f.fovH*60));if(fit>1.8)return{score:45,label:`${Math.ceil(fit)}-panel mosaic`};if(fit>1.05)return{score:70,label:'Tight / mosaic'};if(fit<.04)return{score:35,label:'Very small'};if(fit<.12)return{score:62,label:'Small framing'};return{score:100,label:'Good framing'}}
function evaluateTarget(o,n){
  const hs=hoursForNight(n),fr=framing(o),lpFit=lightPollutionFit(o);let rows=hs.map(h=>{const pos=azAlt(h.time,o),moon=moonAt(h.time),sep=separation(pos,moon),min=state.limits.minAlt,inside=insideSkyWindow(pos.az,pos.alt),altQ=clamp((pos.alt-min)*3.2+35),moonFit=filterFit(o,n.illum.fraction,sep),wq=weatherQuality(h),score=(pos.alt<min||!inside)?0:Math.round(wq*.40+altQ*.22+moonFit*.16+fr.score*.10+lpFit*.12);return{...h,...pos,moonAlt:moon.alt,moonSep:sep,score,minAlt:min,insideWindow:inside,lpFit}});
  const windowRows=rows.filter(x=>x.insideWindow),geometric=windowRows.filter(x=>x.alt>=x.minAlt),usable=geometric.filter(x=>x.score>=60),max=rows.reduce((a,b)=>a.alt>b.alt?a:b,rows[0]||{alt:0}),rankRows=[...geometric].sort((a,b)=>b.score-a.score).slice(0,Math.min(3,geometric.length)),rank=rankRows.length?Math.round(rankRows.reduce((s,x)=>s+x.score,0)/rankRows.length):0,bestInside=[...geometric].sort((a,b)=>b.score-a.score)[0]||null;
  return{target:o,rows,score:rank,hours:usable.length,windowHours:windowRows.length,geometryHours:geometric.length,maxAlt:max.alt||0,transit:max.time,framing:fr,best:bestWindow(usable),bestInside,reason:targetReason(o,windowRows,geometric,usable,bestInside,n)};
}
function targetReason(o,windowRows,geometric,usable,best,n){if(!windowRows.length)return'Outside the measured sky window tonight';if(!geometric.length)return`Inside your sky window, but below your ${state.limits.minAlt}° minimum altitude`;if(usable.length)return`${usable.length} weather-usable hour${usable.length===1?'':'s'} above ${state.limits.minAlt}° inside the window`;const reasons=[];if(best){if(best.cloud>state.limits.cloud)reasons.push(`${Math.round(best.cloud)}% cloud`);if(best.gust>rig().wind)reasons.push(`${Math.round(best.gust)} km/h gusts`);if(best.precipProb>20)reasons.push(`${Math.round(best.precipProb)}% rain risk`);if(best.temp-best.dew<state.limits.dew)reasons.push('dew risk');if(filterFit(o,n.illum.fraction,best.moonSep)<55)reasons.push('filter/Moon mismatch');if(best.lpFit<70)reasons.push('light pollution')}return`Inside the window and above ${state.limits.minAlt}°, but no hour reaches 60/100${reasons.length?' — best hour limited by '+reasons.join(', '):` — best combined hour is ${best?.score||0}/100`}`}
function bestWindow(rows){if(!rows.length)return null;const blocks=[];let b=[rows[0]];for(let i=1;i<rows.length;i++){if(rows[i].time-rows[i-1].time<=1.1*3600000)b.push(rows[i]);else{blocks.push(b);b=[rows[i]]}}blocks.push(b);return blocks.map(x=>({start:x[0].time,end:new Date(x.at(-1).time.getTime()+3600000),duration:(x.at(-1).time-x[0].time)/3600000+1,avg:Math.round(x.reduce((s,h)=>s+h.score,0)/x.length)})).sort((a,b)=>b.duration-a.duration||b.avg-a.avg)[0]}
function modelConfidence(n,hs){let base=94-Math.max(0,(n.midpoint-new Date())/DAY)*6;if(!weather.modelSpread)return clamp(Math.round(base-12));const keys=Object.keys(weather.modelSpread).filter(k=>k.startsWith('cloud_cover_'));if(keys.length<2)return clamp(Math.round(base-10));let devs=[];hs.forEach(h=>{const idx=weather.hourly.time.findIndex(s=>parseWeatherTime(s).getTime()===h.time.getTime());const vals=keys.map(k=>weather.modelSpread[k]?.[idx]).filter(Number.isFinite);if(vals.length>1)devs.push(Math.max(...vals)-Math.min(...vals))});const spread=devs.length?devs.reduce((a,b)=>a+b,0)/devs.length:20;return clamp(Math.round(base-spread*.7))}
function summarizeNight(n){const hs=hoursForNight(n),w=hs.map(weatherQuality),weatherScore=w.length?Math.round(w.reduce((a,b)=>a+b,0)/w.length):0;const evals=DSO.map(o=>evaluateTarget(o,n)).sort((a,b)=>b.score-a.score);const chosen=evals.find(e=>e.target.name===state.selectedTarget)||evals[0],confidence=modelConfidence(n,hs),overall=Math.round(weatherScore*.48+chosen.score*.42+confidence*.10);return{night:n,hours:hs,weatherScore,confidence,chosen,evals,overall,best:chosen.best}}

function renderAll(){if(!weather)return;const base=new Date(state.selectedDate+'T12:00:00Z');nights=Array.from({length:7},(_,i)=>{const d=new Date(base.getTime()+i*DAY);return summarizeNight(makeNight(fmtDate(d)))});renderDashboard(nights[0]);renderTargets();fillPlaces();fillRig();renderPlan()}
function renderStatic(){$('nightDate').value=state.selectedDate;$('minTargetAlt').value=state.limits.minAlt;$('cloudLimit').value=state.limits.cloud;$('dewLimit').value=state.limits.dew;$('windowLimit').value=state.limits.window;switchView(state.activeView)}
function renderDashboard(s){
  const p=place(),r=rig(),e=s.chosen,b=s.best;$('placeButton').textContent=`📍 ${p.name} · B${p.bortle||'?'}${p.sqm?' · '+p.sqm+' SQM':''}`;
  const age=(Date.now()-new Date(weather.fetchedAt||Date.now()))/60000;$('freshness').textContent=age<2?'Updated now':`Updated ${Math.round(age)}m ago`;
  $('weatherScore').textContent=s.weatherScore;$('targetScore').textContent=e.score;$('confidenceScore').textContent=s.confidence;$('imagingScore').textContent=s.overall;document.querySelector('.score-ring').style.setProperty('--score',s.overall+'%');
  $('weatherWhy').textContent=weatherWhy(s.hours);$('targetWhy').textContent=e.target.name;$('confidenceWhy').textContent=s.confidence>75?'Models mostly agree':s.confidence>55?'Some uncertainty':'Low confidence';
  $('decision').textContent=s.overall>=75?`Shoot ${e.target.name}`:s.overall>=55?`${e.target.name} is possible`:'Consider skipping or monitor conditions';
  $('decisionReason').textContent=`${r.name} · ${e.framing.label} · Moon ${Math.round(s.night.illum.fraction*100)}% · max ${Math.round(e.maxAlt)}°`;
  $('bestWindow').textContent=b?`${siteFmt(b.start)} → ${siteFmt(b.end)}`:'No reliable window';$('bestDuration').textContent=b?`${round(b.duration,1)} h`:'0 h';$('dashboardAstroNight').textContent=`${siteFmt(s.night.dusk)} → ${siteFmt(s.night.dawn)}`;$('dashboardAstroDuration').textContent=`${round((s.night.dawn-s.night.dusk)/3600000,1)} h`;$('timelineTitle').textContent=e.target.name;
  renderMainWindow(e);renderTimeline(e,s);renderNotes(s);renderNights();
}
function renderMainWindow(e){const w=skyWindow(),azSpan=w.left<=w.right?w.right-w.left:360-w.left+w.right,inside=e.rows.filter(x=>x.insideWindow&&x.alt>=x.minAlt),entry=inside[0]?.time,exit=inside.length?new Date(inside.at(-1).time.getTime()+3600000):null;$('mainWindowToggle').checked=w.enabled;$('mainWindowTitle').textContent=w.enabled?'Window filtering active':'Window filtering disabled';$('mainWindowDetails').innerHTML=`<div><span>Horizontal opening</span><strong>${Math.round(w.left)}° → ${Math.round(w.right)}°</strong><small>${Math.round(azSpan)}° wide</small></div><div><span>Vertical opening</span><strong>${Math.round(w.bottom)}° → ${Math.round(w.top)}°</strong><small>${Math.round(w.top-w.bottom)}° high</small></div><div><span>Selected target</span><strong>${e.target.name}</strong></div><div><span>Inside tonight</span><strong>${entry?siteFmt(entry)+'–'+siteFmt(exit):'Never'}</strong></div>`;$('mainWindowTarget').textContent=w.enabled?(entry?`${e.target.name} enters your measured opening at ${siteFmt(entry)} and leaves at ${siteFmt(exit)}.`:`${e.target.name} does not enter your measured opening tonight.`):'Turn on the switch to apply this window to target ranking and session planning.'}
function weatherWhy(hs){if(!hs.length)return'No forecast data';const c=Math.round(hs.reduce((s,h)=>s+h.cloud,0)/hs.length),g=Math.round(Math.max(...hs.map(h=>h.gust)));return`${c}% cloud avg · ${g} km/h max gust`}
function renderTimeline(e,s){
  if(timelineChart)timelineChart.destroy();const labels=e.rows.map(x=>siteFmt(x.time)),w=skyWindow(),azVisible=e.rows.map(x=>insideWindowAz(x.az));
  timelineChart=new Chart($('timelineChart'),{type:'line',data:{labels,datasets:[
    {label:'Window bottom',data:e.rows.map((x,i)=>w.enabled&&azVisible[i]?w.bottom:null),borderColor:'#34d399',backgroundColor:'#34d3991c',borderDash:[4,3],pointRadius:0,spanGaps:false},
    {label:'Available sky window',data:e.rows.map((x,i)=>w.enabled&&azVisible[i]?w.top:null),borderColor:'#34d399',backgroundColor:'#34d3991c',fill:'-1',borderDash:[4,3],pointRadius:0,spanGaps:false},
    {label:'Cloud %',data:e.rows.map(x=>x.cloud),borderColor:'#64748b',backgroundColor:'#64748b22',fill:true,pointRadius:0,tension:.25},
    {label:'Target altitude',data:e.rows.map(x=>Math.max(0,x.alt)),borderColor:'#38bdf8',backgroundColor:'#38bdf822',pointRadius:0,borderWidth:3,tension:.25},
    {label:'Minimum target altitude',data:e.rows.map(()=>state.limits.minAlt),borderColor:'#fb7185',borderDash:[3,3],pointRadius:0},
    {label:'Moon altitude',data:e.rows.map(x=>Math.max(0,x.moonAlt)),borderColor:'#e2e8f0',borderDash:[6,4],pointRadius:0},
    {label:'Wind gust km/h',data:e.rows.map(x=>x.gust),borderColor:'#f59e0b',borderDash:[2,3],pointRadius:0}
  ]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:true,position:'top',labels:{color:'#a8bad0',usePointStyle:true,pointStyle:'rectRounded',boxWidth:10,padding:14,filter:item=>item.text!=='Window bottom'},onClick:(event,item,legend)=>{const chart=legend.chart;if(item.datasetIndex===1){const hidden=chart.isDatasetVisible(1);chart.setDatasetVisibility(0,!hidden);chart.setDatasetVisibility(1,!hidden);chart.update()}else Chart.defaults.plugins.legend.onClick(event,item,legend)}},tooltip:{callbacks:{afterBody:items=>{const x=e.rows[items[0].dataIndex];return[`Azimuth ${Math.round(x.az)}°`,x.insideWindow?'Inside measured window':'Outside measured window',`Combined score ${x.score}/100`,`Dew gap ${round(x.temp-x.dew,1)}°C`,`Moon separation ${Math.round(x.moonSep)}°`]}}}},scales:{x:{ticks:{color:'#8ca0b9',maxTicksLimit:10},grid:{color:'#ffffff0a'}},y:{min:0,max:100,ticks:{color:'#8ca0b9'},grid:{color:'#ffffff0a'}}}}})
}
function renderNotes(s){const hs=s.hours,notes=[];if(!hs.length)notes.push(['⚠','No hourly weather data for this night.']);else{const minGap=Math.min(...hs.map(h=>h.temp-h.dew)),dewAt=hs.find(h=>h.temp-h.dew===minGap);if(minGap<state.limits.dew+1)notes.push(['💧',`Dew gap reaches ${round(minGap,1)}°C near ${siteFmt(dewAt.time)}. Start heaters early.`]);const gust=Math.max(...hs.map(h=>h.gust));if(gust>rig().wind)notes.push(['🌬',`Gusts reach ${Math.round(gust)} km/h, above this rig’s ${rig().wind} km/h limit.`]);const rain=Math.max(...hs.map(h=>h.precipProb));if(rain>20)notes.push(['🌧',`Precipitation probability reaches ${Math.round(rain)}%.`]);if(s.night.illum.fraction>.55)notes.push(['☾',`${Math.round(s.night.illum.fraction*100)}% Moon; target-specific separation and filter are included.`]);if(s.confidence<65)notes.push(['≈','Forecast confidence is limited; recheck close to setup time.'])}if(!notes.length)notes.push(['✓','No major equipment-risk conditions detected.']);$('nightNotes').innerHTML=notes.map(n=>`<div class="note"><b>${n[0]}</b><span>${n[1]}</span></div>`).join('')}
function renderNights(){$('nightList').innerHTML=nights.map((s,i)=>`<button class="night card ${i===0?'selected':''}" data-i="${i}"><small>${siteFmt(s.night.midpoint,{weekday:'short'})}</small><strong>${s.overall}</strong><span>${Math.round(s.night.illum.fraction*100)}% ☾</span><small>${s.best?round(s.best.duration,1)+'h':'No window'}</small></button>`).join('');document.querySelectorAll('.night').forEach(b=>b.onclick=()=>{state.selectedDate=nights[+b.dataset.i].night.date;$('nightDate').value=state.selectedDate;save();renderAll()})}

function renderTargets(){if(!nights.length)return;const q=$('targetSearch').value.toLowerCase(),type=$('targetType').value,bm=$('bookmarksOnly').checked;evaluations=nights[0].evals.filter(e=>(!q||e.target.name.toLowerCase().includes(q))&&(type==='all'||e.target.type===type)&&(!bm||state.bookmarks.includes(e.target.name)));$('targetList').innerHTML=evaluations.map(e=>{const windowRows=e.rows.filter(x=>x.insideWindow&&x.alt>=x.minAlt),entry=windowRows[0]?.time,exit=windowRows.length?new Date(windowRows.at(-1).time.getTime()+3600000):null;return`<article class="target-card card" data-id="${e.target.id}"><div><span class="pill">${e.target.type}</span><h3>${e.target.name}</h3><div class="target-meta">${e.framing.label} · rank ${e.score}/100 · ${e.hours}h weather-usable · max ${Math.round(e.maxAlt)}°</div><div class="target-meta ${entry?'inside-window':'outside-window'}">${entry?`Inside your sky window ${siteFmt(entry)}–${siteFmt(exit)}`:'Not inside your sky window tonight'}</div><div class="target-meta">${e.reason}</div></div><div><button class="bookmark" data-bookmark="${e.target.id}">${state.bookmarks.includes(e.target.name)?'★':'☆'}</button><div class="target-score">${e.score}</div></div></article>`}).join('')||'<article class="card muted">No matching targets.</article>';document.querySelectorAll('.target-card').forEach(c=>c.onclick=e=>{if(e.target.closest('.bookmark'))return;showTarget(+c.dataset.id)});document.querySelectorAll('.bookmark').forEach(b=>b.onclick=()=>toggleBookmark(+b.dataset.bookmark))}
function toggleBookmark(id){const n=DSO[id].name;state.bookmarks=state.bookmarks.includes(n)?state.bookmarks.filter(x=>x!==n):[...state.bookmarks,n];save();renderTargets()}

function compositionKey(target){return`${rig().id}:${target.id}`}
function initComposition(target){
  compositionTarget=target;const saved=state.compositions?.[compositionKey(target)];frameState={x:saved?.x??50,y:saved?.y??50,rotation:saved?.rotation??0,survey:saved?.survey||'P/DSS2/color'};$('surveySelect').value=frameState.survey;
  const box=$('aladinContainer'),o=optics(),aspect=box.clientWidth/box.clientHeight;compositionViewFov=Math.max(o.fovW*1.65,o.fovH*1.65*aspect,target.w/60*1.15,target.h/60*1.15*aspect);const frame=$('fovFrame');frame.style.width=`${Math.min(88,o.fovW/compositionViewFov*100)}%`;frame.style.height=`${Math.min(88,o.fovH/(compositionViewFov/aspect)*100)}%`;frame.querySelector('.frame-label').textContent=`${rig().name} · ${round(o.fovW,2)}° × ${round(o.fovH,2)}°`;
  applyFrame();bindFrameDrag();$('compositionStatus').textContent='Loading astronomical survey image…';
  if(!window.A){$('compositionStatus').textContent='Survey viewer could not load. Check the internet connection and refresh.';return}
  A.init.then(()=>{try{if(!aladin){aladin=A.aladin('#aladinView',{survey:frameState.survey,target:`${target.ra} ${target.dec}`,fov:compositionViewFov,showLayersControl:false,showFullscreenControl:false,showReticle:false,showCooGridControl:false,showSimbadPointerControl:false})}else{aladin.gotoRaDec(target.ra,target.dec);aladin.setFov(compositionViewFov);changeSurvey()}updateCompositionStatus()}catch{$('compositionStatus').textContent='The survey image is temporarily unavailable.'}});
}
function bindFrameDrag(){const frame=$('fovFrame');frame.onpointerdown=e=>{e.preventDefault();frame.setPointerCapture(e.pointerId);const box=$('aladinContainer').getBoundingClientRect(),start={clientX:e.clientX,clientY:e.clientY,x:frameState.x,y:frameState.y};frame.onpointermove=move=>{const halfX=frame.offsetWidth/box.width*50,halfY=frame.offsetHeight/box.height*50;frameState.x=clamp(start.x+(move.clientX-start.clientX)/box.width*100,halfX,100-halfX);frameState.y=clamp(start.y+(move.clientY-start.clientY)/box.height*100,halfY,100-halfY);applyFrame();updateCompositionStatus()};frame.onpointerup=()=>{frame.onpointermove=null;frame.onpointerup=null}}}
function applyFrame(){const frame=$('fovFrame');frame.style.left=`${frameState.x}%`;frame.style.top=`${frameState.y}%`;frame.style.transform=`translate(-50%,-50%) rotate(${frameState.rotation}deg)`;$('rotationSlider').value=frameState.rotation;$('rotationValue').textContent=`${Math.round(frameState.rotation)}°`}
function updateCompositionStatus(){if(!compositionTarget||!frameState)return;const aspect=$('aladinContainer').clientWidth/$('aladinContainer').clientHeight,dx=(frameState.x-50)/100*compositionViewFov,dy=-(frameState.y-50)/100*(compositionViewFov/aspect),raOffset=dx/Math.max(.15,Math.cos(rad(compositionTarget.dec)));$('compositionStatus').textContent=`Frame centre offset: ΔRA ${raOffset>=0?'+':''}${round(raOffset,2)}°, ΔDec ${dy>=0?'+':''}${round(dy,2)}° · position angle ${Math.round(frameState.rotation)}°. Drag to compose, then save.`}
function saveComposition(){if(!compositionTarget)return;state.compositions||={};state.compositions[compositionKey(compositionTarget)]={...frameState,savedAt:new Date().toISOString()};save();toast('Composition saved for this target and rig');updateCompositionStatus()}
function changeSurvey(){if(!frameState)return;frameState.survey=$('surveySelect').value;if(!aladin)return;try{if(typeof aladin.setImageSurvey==='function')aladin.setImageSurvey(frameState.survey);else if(typeof aladin.setBaseImageLayer==='function')aladin.setBaseImageLayer(frameState.survey)}catch{}updateCompositionStatus()}
function showTarget(id){const e=nights[0].evals.find(x=>x.target.id===id),w=skyWindow(),windowRows=e.rows.filter(x=>x.insideWindow&&x.alt>=x.minAlt),entry=windowRows[0]?.time,exit=windowRows.length?new Date(windowRows.at(-1).time.getTime()+3600000):null;state.selectedTarget=e.target.name;save();$('targetDetail').innerHTML=`<p class="eyebrow">${e.target.type}</p><h2>${e.target.name}</h2><p class="muted">Rank ${e.score}/100 · ${e.framing.label} · ${round(e.hours,1)} weather-usable hours · transit ${siteFmt(e.transit)} at ${Math.round(e.maxAlt)}°.</p><p class="${e.hours?'inside-window':'outside-window'}">${e.reason}</p><div class="data-grid"><div><span>Inside measured window</span><strong>${entry?siteFmt(entry)+'–'+siteFmt(exit):'Never tonight'}</strong></div><div><span>Apparent size</span><strong>${e.target.w}' × ${e.target.h}'</strong></div><div><span>Your FOV</span><strong>${round(optics().fovW,2)}° × ${round(optics().fovH,2)}°</strong></div><div><span>Best weather window</span><strong>${e.best?siteFmt(e.best.start)+'–'+siteFmt(e.best.end):'None ≥60'}</strong></div></div><button class="primary wide" id="selectTarget">Use as selected target</button>`;$('targetDialog').showModal();setTimeout(()=>{$('selectTarget').onclick=()=>{$('targetDialog').close();renderAll();toast('Target selected')};initComposition(e.target);if(targetChart)targetChart.destroy();const azVisible=e.rows.map(x=>insideWindowAz(x.az));targetChart=new Chart($('targetChart'),{type:'line',data:{labels:e.rows.map(x=>siteFmt(x.time)),datasets:[{label:'Window bottom',data:e.rows.map((x,i)=>azVisible[i]&&w.enabled?w.bottom:null),borderColor:'#34d399',backgroundColor:'#34d39922',borderDash:[3,3],pointRadius:0,spanGaps:false},{label:'Available sky window',data:e.rows.map((x,i)=>azVisible[i]&&w.enabled?w.top:null),borderColor:'#34d399',backgroundColor:'#34d39922',fill:'-1',borderDash:[3,3],pointRadius:0,spanGaps:false},{label:'Target altitude',data:e.rows.map(x=>Math.max(0,x.alt)),borderColor:'#38bdf8',backgroundColor:'#38bdf822',pointRadius:0,borderWidth:3},{label:'Minimum target altitude',data:e.rows.map(x=>x.minAlt),borderColor:'#fb7185',borderDash:[3,3],pointRadius:0},{label:'Moon altitude',data:e.rows.map(x=>Math.max(0,x.moonAlt)),borderColor:'#e2e8f0',borderDash:[5,5],pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},scales:{x:{ticks:{color:'#8ca0b9'}},y:{min:0,max:90,ticks:{color:'#8ca0b9'}}},plugins:{legend:{labels:{color:'#8ca0b9',filter:item=>item.text!=='Window bottom'}},tooltip:{callbacks:{afterBody:items=>{const x=e.rows[items[0].dataIndex];return[`Azimuth ${Math.round(x.az)}°`,x.insideWindow?'Inside measured window':'Outside measured window',`Combined hour score ${x.score}/100`]}}}}}})},30)}

function buildPlan(){if(!nights.length)return;const s=nights[0],favorites=s.evals.filter(e=>state.bookmarks.includes(e.target.name)&&e.score>0);const pool=(favorites.length?favorites:s.evals.slice(0,8));const slots=s.hours.map(h=>{const options=pool.map(e=>e.rows.find(x=>x.time.getTime()===h.time.getTime())).map((x,i)=>({row:x,e:pool[i]})).filter(x=>x.row?.score>=60).sort((a,b)=>b.row.score-a.row.score);return options[0]?{time:h.time,e:options[0].e,row:options[0].row}:null});const groups=[];for(const slot of slots){const last=groups.at(-1);if(slot&&last&&last.target===slot.e.target.name&&slot.time-last.last<=1.1*3600000){last.last=slot.time;last.rows.push(slot.row)}else if(slot)groups.push({target:slot.e.target.name,filter:recommendFilter(slot.e.target),start:slot.time,last:slot.time,rows:[slot.row],transit:slot.e.transit})}state.currentPlan=groups.filter(g=>g.rows.length>=Math.ceil(state.limits.window)).map(g=>({...g,end:new Date(g.last.getTime()+3600000),score:Math.round(g.rows.reduce((s,x)=>s+x.score,0)/g.rows.length)}));state.currentPlanDate=state.selectedDate;renderPlan()}
function recommendFilter(o){if(o.signal==='broadband')return'Broadband';if(rig().filter==='siioiii')return'Askar E2 (SII+OIII)';if(rig().filter==='haoiii')return'L-Ultimate (Ha+OIII)';return o.signal==='oiii'?'OIII':'Narrowband'}
function planItemDates(g){return{...g,start:new Date(g.start),end:new Date(g.end),transit:g.transit?new Date(g.transit):null}}
function openPlan(){const saved=state.plans[state.selectedDate];if(state.currentPlanDate!==state.selectedDate){state.currentPlan=(saved?.items||[]).map(planItemDates);state.currentPlanDate=state.selectedDate}renderPlan()}
function renderPlan(){const s=nights[0],plan=(state.currentPlan||[]).map(planItemDates);state.currentPlan=plan;$('planTitle').textContent=`${place().name} · ${state.selectedDate}`;$('astroNightHours').textContent=s?`${siteFmt(s.night.dusk)}–${siteFmt(s.night.dawn)}`:'—';$('astroNightDuration').textContent=s?`${round((s.night.dawn-s.night.dusk)/3600000,1)} hours available; targets outside this period receive no suggestion.`:'—';$('manualTargetSelect').innerHTML=(s?.evals||[]).map(e=>`<option value="${e.target.id}">${e.target.name} · ${e.score}/100</option>`).join('');$('planList').innerHTML=plan.length?plan.map((g,i)=>`<article class="plan-item editable"><time>${siteFmt(g.start)}–${siteFmt(g.end)}</time><div><strong>${g.target}</strong><p class="muted">${g.filter} · score ${g.score??'manual'} · ${round((g.end-g.start)/3600000,1)} hours${g.transit&&g.transit>=g.start&&g.transit<=g.end?' · meridian crossing '+siteFmt(g.transit):''}</p></div><div class="plan-actions"><button class="ghost" data-plan-shift="${i},-30" title="30 minutes earlier">−30m</button><button class="ghost" data-plan-shift="${i},30" title="30 minutes later">+30m</button><button class="ghost" data-plan-up="${i}" title="Move up">↑</button><button class="ghost" data-plan-down="${i}" title="Move down">↓</button><button class="ghost danger" data-plan-delete="${i}">Delete</button></div></article>`).join(''):'<article class="card muted">No targets in this plan. Generate an automatic plan or add a target manually.</article>';const saved=state.plans[state.selectedDate];$('planNotes').value=saved?.notes||$('planNotes').value||'';document.querySelectorAll('[data-plan-delete]').forEach(b=>b.onclick=()=>{state.currentPlan.splice(+b.dataset.planDelete,1);renderPlan()});document.querySelectorAll('[data-plan-shift]').forEach(b=>b.onclick=()=>{const [i,m]=b.dataset.planShift.split(',').map(Number),g=state.currentPlan[i],delta=m*60000;g.start=new Date(g.start.getTime()+delta);g.end=new Date(g.end.getTime()+delta);renderPlan()});document.querySelectorAll('[data-plan-up]').forEach(b=>b.onclick=()=>movePlanItem(+b.dataset.planUp,-1));document.querySelectorAll('[data-plan-down]').forEach(b=>b.onclick=()=>movePlanItem(+b.dataset.planDown,1))}
function addManualPlanTarget(){const e=nights[0]?.evals.find(x=>x.target.id===+$('manualTargetSelect').value);if(e)addTargetToPlan(e.target.name)}
function addTargetToPlan(name){const s=nights[0],e=s?.evals.find(x=>x.target.name===name);if(!e)return;const start=e.best?.start||s.night.dusk,end=e.best?.end||new Date(Math.min(s.night.dawn,new Date(start).getTime()+3600000));state.currentPlanDate=state.selectedDate;state.currentPlan||=[];state.currentPlan.push({target:name,filter:recommendFilter(e.target),start:new Date(start),end:new Date(end),score:e.score,transit:e.transit});state.currentPlan.sort((a,b)=>new Date(a.start)-new Date(b.start));renderPlan();toast(`${name} added to plan`)}
function movePlanItem(i,d){const j=i+d;if(j<0||j>=state.currentPlan.length)return;[state.currentPlan[i],state.currentPlan[j]]=[state.currentPlan[j],state.currentPlan[i]];renderPlan()}
function clearPlan(){state.currentPlan=[];state.currentPlanDate=state.selectedDate;renderPlan();toast('Plan cleared')}
function savePlan(){state.plans[state.selectedDate]={items:(state.currentPlan||[]).map(planItemDates),notes:$('planNotes').value,savedAt:new Date().toISOString()};save();toast('Plan and notes saved on this device')}
function exportPlan(){const rows=[['Start','End','Target','Filter','Score'],...(state.currentPlan||[]).map(g=>[siteFmt(g.start),siteFmt(g.end),g.target,g.filter,g.score])];const blob=new Blob([rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`astrowindow-${state.selectedDate}.csv`;a.click();URL.revokeObjectURL(a.href)}

function fillPlaces(){$('placeList').innerHTML=state.places.map(p=>{const w=p.window||{enabled:false,left:0,right:360,bottom:state.limits.minAlt,top:90},lp=p.sqm?`${p.sqm} SQM${p.bortle?' · Bortle '+p.bortle:''}`:p.bortle?`Bortle ${p.bortle}`:'Light pollution not set';return`<article class="saved-site card ${p.id===state.activePlace?'active':''}"><div class="saved-site-head"><div><h3>${p.name}</h3><small>${p.lat.toFixed(5)}, ${p.lon.toFixed(5)}</small></div><span class="pill">${p.id===state.activePlace?'ACTIVE':'SAVED'}</span></div><div class="site-data"><div><span>Light pollution</span><strong>${lp}</strong></div><div><span>Custom sky window</span><strong>${w.enabled?`${Math.round(w.left)}°→${Math.round(w.right)}° · ${Math.round(w.bottom)}°→${Math.round(w.top)}°`:'Not active'}</strong></div></div><div class="site-actions"><button class="primary" data-place="${p.id}">Use site</button><button class="ghost" data-window-place="${p.id}">Sky window</button><button class="ghost" data-edit-place="${p.id}">Edit / map</button><a class="ghost" target="_blank" rel="noopener" href="${lightPollutionUrl(p.lat,p.lon)}">LP estimate ↗</a>${state.places.length>1?`<button class="ghost danger" data-remove-place="${p.id}">Delete</button>`:''}</div></article>`}).join('');document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>{state.activePlace=+b.dataset.place;save();refresh();switchView('dashboard')});document.querySelectorAll('[data-window-place]').forEach(b=>b.onclick=()=>{state.activePlace=+b.dataset.windowPlace;save();fillRig();switchView('settings')});document.querySelectorAll('[data-edit-place]').forEach(b=>b.onclick=()=>openMapPicker(+b.dataset.editPlace));document.querySelectorAll('[data-remove-place]').forEach(b=>b.onclick=()=>{state.places=state.places.filter(p=>p.id!==+b.dataset.removePlace);if(state.activePlace===+b.dataset.removePlace)state.activePlace=state.places[0].id;save();fillPlaces()})}
function lightPollutionUrl(lat,lon){return`https://lightpollutionmap.app/?lat=${encodeURIComponent(lat)}&lng=${encodeURIComponent(lon)}&zoom=12`}
function addPlace(e){e.preventDefault();const p={id:Date.now(),name:$('placeName').value,lat:+$('placeLat').value,lon:+$('placeLon').value,bortle:+$('placeBortle').value||null,sqm:+$('placeSqm').value||null,window:{enabled:false,left:0,right:360,bottom:20,top:90}};state.places.push(p);state.activePlace=p.id;save();e.target.reset();fillPlaces();refresh()}
function useGPS(){navigator.geolocation?.getCurrentPosition(pos=>{const p={id:Date.now(),name:'GPS observing site',lat:pos.coords.latitude,lon:pos.coords.longitude,bortle:null,sqm:null,window:{enabled:false,left:0,right:360,bottom:20,top:90}};state.places.push(p);state.activePlace=p.id;save();fillPlaces();refresh();toast('GPS site added')},()=>toast('Location permission was not available'),{enableHighAccuracy:true,timeout:10000})}

function openMapPicker(editId=null){if(!window.L){toast('Map library could not load');return}mapEditingId=editId;const p=editId?state.places.find(x=>x.id===editId):place();mapSelection={lat:p.lat,lon:p.lon};$('mapPlaceName').value=editId?p.name:'';$('mapBortle').value=editId?(p.bortle||''):'';$('mapSqm').value=editId?(p.sqm||''):'';$('mapSearchInput').value='';$('saveMapLocation').textContent=editId?'Update observing site':'Save as active observing site';$('mapDialog').showModal();setTimeout(()=>{if(!locationMap){locationMap=L.map('locationMap',{zoomControl:true}).setView([p.lat,p.lon],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(locationMap);locationMap.on('click',e=>setMapPoint(e.latlng.lat,e.latlng.lng,true));locationMarker=L.marker([p.lat,p.lon],{draggable:true}).addTo(locationMap);locationMarker.on('dragend',e=>{const c=e.target.getLatLng();setMapPoint(c.lat,c.lng,false)})}else{locationMap.setView([p.lat,p.lon],10);locationMap.invalidateSize()}setMapPoint(p.lat,p.lon,false)},80)}
function closeMapPicker(){if($('mapDialog').open)$('mapDialog').close()}
function setMapPoint(lat,lon,clearName=false){mapSelection={lat,lon};if(locationMarker)locationMarker.setLatLng([lat,lon]);$('mapCoordinates').textContent=`${lat.toFixed(6)}, ${lon.toFixed(6)}`;$('mapLightPollutionLink').href=lightPollutionUrl(lat,lon);if(clearName&&!$('mapPlaceName').value)$('mapPlaceName').placeholder=`Map point ${lat.toFixed(3)}, ${lon.toFixed(3)}`}
async function searchMapPlace(){const q=$('mapSearchInput').value.trim();if(!q)return;const button=$('mapSearchButton');button.disabled=true;button.textContent='Searching…';try{const r=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=1&language=en&format=json`),j=await r.json();if(!j.results?.length){toast('Location not found');return}const x=j.results[0];setMapPoint(x.latitude,x.longitude,false);$('mapPlaceName').value=[x.name,x.admin1,x.country].filter(Boolean).join(', ');locationMap.setView([x.latitude,x.longitude],Math.max(locationMap.getZoom(),11))}catch{toast('Location search failed')}finally{button.disabled=false;button.textContent='Search'}}
function centerMapOnGPS(){if(!navigator.geolocation){toast('GPS is not available');return}navigator.geolocation.getCurrentPosition(pos=>{setMapPoint(pos.coords.latitude,pos.coords.longitude,false);locationMap.setView([pos.coords.latitude,pos.coords.longitude],15);if(!$('mapPlaceName').value)$('mapPlaceName').value='GPS observing site'},()=>toast('Location permission was not available'),{enableHighAccuracy:true,timeout:10000})}
function saveMapLocation(){if(!mapSelection){toast('Choose a point on the map first');return}const old=mapEditingId?state.places.find(p=>p.id===mapEditingId):null,name=$('mapPlaceName').value.trim()||`Map site ${mapSelection.lat.toFixed(3)}, ${mapSelection.lon.toFixed(3)}`,p={id:old?.id||Date.now(),name,lat:mapSelection.lat,lon:mapSelection.lon,bortle:+$('mapBortle').value||null,sqm:+$('mapSqm').value||null,window:old?.window||{enabled:false,left:0,right:360,bottom:state.limits.minAlt,top:90}};if(old)Object.assign(old,p);else state.places.push(p);state.activePlace=p.id;mapEditingId=null;save();closeMapPicker();fillPlaces();refresh();switchView('dashboard');toast(old?'Observing site updated':'Map location saved and activated')}

function fillRig(){$('rigSelect').innerHTML=state.rigs.map(r=>`<option value="${r.id}" ${r.id===state.activeRig?'selected':''}>${r.name}</option>`).join('');const r=rig();$('rigName').value=r.name;$('focalLength').value=r.focal;$('aperture').value=r.aperture;$('sensorWidth').value=r.sensorW;$('sensorHeight').value=r.sensorH;$('pixelSize').value=r.pixel;$('filter').value=r.filter;$('mount').value=r.mount;$('windLimit').value=r.wind;const w=skyWindow();$('winLeft').value=w.left;$('winRight').value=w.right;$('winBottom').value=w.bottom;$('winTop').value=w.top;$('windowEnabled').checked=w.enabled;renderWindowSummary();const o=optics();$('opticsSummary').innerHTML=`<div><span>Focal ratio</span><strong>f/${round(o.fRatio,1)}</strong></div><div><span>Image scale</span><strong>${round(o.scale,2)}″/px</strong></div><div><span>Field of view</span><strong>${round(o.fovW,2)}° × ${round(o.fovH,2)}°</strong></div><div><span>Sampling</span><strong>${o.scale>2?'Wide / undersampled':o.scale<.6?'Fine / seeing-sensitive':'Balanced'}</strong></div>`}
function saveRig(e){e.preventDefault();Object.assign(rig(),{name:$('rigName').value,focal:+$('focalLength').value,aperture:+$('aperture').value,sensorW:+$('sensorWidth').value,sensorH:+$('sensorHeight').value,pixel:+$('pixelSize').value,filter:$('filter').value,mount:$('mount').value,wind:+$('windLimit').value});save();fillRig();renderAll();toast('Rig profile saved')}
function newRig(){const r={...structuredClone(rig()),id:Date.now(),name:'New rig profile'};state.rigs.push(r);state.activeRig=r.id;save();fillRig()}
function saveHorizon(){const left=normalizeAz(+$('winLeft').value),right=normalizeAz(+$('winRight').value),bottom=+$('winBottom').value,top=+$('winTop').value;if(top<=bottom){toast('Top altitude must be higher than bottom');return}place().window={enabled:$('windowEnabled').checked,left,right,bottom,top};save();renderWindowSummary();renderAll();toast('Available sky window saved for this site')}
function normalizeAz(x){return((x%360)+360)%360}
function renderWindowSummary(){const w={enabled:$('windowEnabled').checked,left:+$('winLeft').value,right:+$('winRight').value,bottom:+$('winBottom').value,top:+$('winTop').value},span=w.left<=w.right?w.right-w.left:360-w.left+w.right;$('windowSummary').innerHTML=w.enabled?`Active window: <strong>${Math.round(span)}° wide</strong>, azimuth ${Math.round(w.left)}° → ${Math.round(w.right)}°, altitude ${Math.round(w.bottom)}° → ${Math.round(w.top)}°. Targets are accepted only while their centre is inside this box.`:'Window filtering is currently disabled.'}

async function startWindowCalibration(){
  if(!('DeviceOrientationEvent' in window)){toast('Orientation sensors are not available on this device');return}
  if(typeof DeviceOrientationEvent.requestPermission==='function'){
    try{if(await DeviceOrientationEvent.requestPermission()!=='granted'){toast('Sensor permission was not granted');return}}catch{toast('Could not access phone sensors');return}
  }
  sensorStep=0;sensorHeading=null;sensorAltitude=null;
  window.addEventListener('deviceorientation',readOrientation,true);$('sensorDialog').showModal();renderSensorStep();
}
function readOrientation(e){
  if(e.alpha!=null)sensorHeading=normalizeAz(Number.isFinite(e.webkitCompassHeading)?e.webkitCompassHeading:360-e.alpha);
  if(e.beta!=null){let beta=e.beta;if(beta>90)beta=180-beta;if(beta<-90)beta=-180-beta;sensorAltitude=clamp(90-Math.abs(beta),-10,90)}
  renderSensorReading();
}
function renderSensorStep(){const s=SENSOR_STEPS[sensorStep];$('sensorStepTitle').textContent=s.title;$('sensorInstructions').textContent=s.instruction;$('captureSensor').textContent=`Capture ${s.key} boundary`;$('sensorProgress').innerHTML=SENSOR_STEPS.map((_,i)=>`<i class="${i<sensorStep?'done':i===sensorStep?'current':''}"></i>`).join('');renderSensorReading()}
function renderSensorReading(){const s=SENSOR_STEPS[sensorStep];if(!s)return;const main=s.value==='heading'?sensorHeading:sensorAltitude,secondary=s.value==='heading'?`Altitude ${sensorAltitude==null?'—':Math.round(sensorAltitude)+'°'}`:`Compass ${sensorHeading==null?'—':Math.round(sensorHeading)+'°'}`;$('sensorValue').textContent=main==null?'—°':`${Math.round(main)}°`;$('sensorSecondary').textContent=secondary}
function captureWindowBoundary(){const s=SENSOR_STEPS[sensorStep],value=s.value==='heading'?sensorHeading:sensorAltitude;if(value==null){toast('Waiting for a valid sensor reading');return}$('win'+s.key[0].toUpperCase()+s.key.slice(1)).value=Math.round(value);sensorStep++;if(sensorStep>=SENSOR_STEPS.length){$('windowEnabled').checked=true;stopWindowCalibration();renderWindowSummary();toast('Four boundaries captured — review and save')}else renderSensorStep()}
function stopWindowCalibration(){window.removeEventListener('deviceorientation',readOrientation,true);if($('sensorDialog').open)$('sensorDialog').close()}
